"""make organization_id nullable in users

Revision ID: 42429b6c6684
Revises: ee85c65317e3
Create Date: 2025-08-02 09:21:03.986651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42429b6c6684'
down_revision = 'ee85c65317e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('is_super_admin',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_super_admin',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               nullable=False)
        batch_op.alter_column('organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###