"""add missing fields like organization_id and is_super_admin

Revision ID: 83015671028d
Revises: 8e4983d3b1e9
Create Date: 2025-08-02 09:00:25.040188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83015671028d'
down_revision = '8e4983d3b1e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_org_table_timestamp')

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_email_org_status_created')

    with op.batch_alter_table('purchase_vouchers', schema=None) as batch_op:
        batch_op.drop_index('idx_voucher_org_date_status')
        batch_op.drop_index('idx_voucher_org_vendor_date')

    with op.batch_alter_table('sales_vouchers', schema=None) as batch_op:
        batch_op.drop_index('idx_sales_voucher_org_customer_date')
        batch_op.drop_index('idx_sales_voucher_org_date_status')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_org_product_quantity')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index('idx_stock_org_product_quantity', ['organization_id', 'product_id', 'quantity'], unique=False)

    with op.batch_alter_table('sales_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_sales_voucher_org_date_status', ['organization_id', 'date', 'status'], unique=False)
        batch_op.create_index('idx_sales_voucher_org_customer_date', ['organization_id', 'customer_id', 'date'], unique=False)

    with op.batch_alter_table('purchase_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_voucher_org_vendor_date', ['organization_id', 'vendor_id', 'date'], unique=False)
        batch_op.create_index('idx_voucher_org_date_status', ['organization_id', 'date', 'status'], unique=False)

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index('idx_email_org_status_created', ['organization_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_org_table_timestamp', ['organization_id', 'table_name', 'timestamp'], unique=False)

    # ### end Alembic commands ###