"""add is_super_admin to users

Revision ID: ee85c65317e3
Revises: 83015671028d
Create Date: 2025-08-02 09:05:35.702506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee85c65317e3'
down_revision = '83015671028d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_org_table_timestamp')

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.drop_index('idx_email_org_status_created')

    with op.batch_alter_table('purchase_vouchers', schema=None) as batch_op:
        batch_op.drop_index('idx_voucher_org_date_status')
        batch_op.drop_index('idx_voucher_org_vendor_date')

    with op.batch_alter_table('sales_vouchers', schema=None) as batch_op:
        batch_op.drop_index('idx_sales_voucher_org_customer_date')
        batch_op.drop_index('idx_sales_voucher_org_date_status')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.drop_index('idx_stock_org_product_quantity')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_super_admin', sa.Boolean(), nullable=False, server_default=sa.text('false')))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_super_admin')

    with op.batch_alter_table('stock', schema=None) as batch_op:
        batch_op.create_index('idx_stock_org_product_quantity', ['organization_id', 'product_id', 'quantity'], unique=False)

    with op.batch_alter_table('sales_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_sales_voucher_org_date_status', ['organization_id', 'date', 'status'], unique=False)
        batch_op.create_index('idx_sales_voucher_org_customer_date', ['organization_id', 'customer_id', 'date'], unique=False)

    with op.batch_alter_table('purchase_vouchers', schema=None) as batch_op:
        batch_op.create_index('idx_voucher_org_vendor_date', ['organization_id', 'vendor_id', 'date'], unique=False)
        batch_op.create_index('idx_voucher_org_date_status', ['organization_id', 'date', 'status'], unique=False)

    with op.batch_alter_table('email_notifications', schema=None) as batch_op:
        batch_op.create_index('idx_email_org_status_created', ['organization_id', 'status', 'created_at'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_org_table_timestamp', ['organization_id', 'table_name', 'timestamp'], unique=False)

    # ### end Alembic commands ###